name: Bug report
description: Message parser doesn't parse right
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for helping to improve DeltaChat! Please fill information below to make it easier to us to understand and solve the issue.
  - type: input
    id: version
    attributes:
      label: Message parser version or commit
      placeholder: v0.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Explaination
      description: Explain about the bug. Optionally explain why do you think it's a bug. Like is it out of sync with some spec?
    validations:
      required: true
  - type: markdown
    attributes:
      value: Each testcase should ideally be a text sample as input, the expected and the actual AST. You can take a look at already existing tests.
  - type: textarea
    id: testcase_0
    attributes:
      label: Testcase 0
      description: Optionally provide a testcase
  - type: textarea
    id: testcase_1
    attributes:
      label: Testcase 1
      description: Optionally provide a testcase
  - type: textarea
    id: testcase_2
    attributes:
      label: Testcase 2
      description: Optionally provide a testcase
